### ISSUE TITLE
Code not working for P_all

### ISSUE THREAD

**Issue by Souvic** [PatriciaXiao/TIMME#1]
>> python main.py -d P_all

using cuda
Loading data from path ../data/P_all
  relations: retweet_list.csv mention_list.csv friend_list.csv reply_list.csv favorite_list.csv
        loading additional labels from 1 files: ../data/additional_labels/new_dict_cleaned.csv
        processing nodes
Traceback (most recent call last):
  File "main.py", line 103, in <module>
    adjs, features, labels_info, trainable, mask, link_info, (label_map, all_id_list) = multi_relation_load(DATA, files=args.relations, \
  File "/home/souvic/HULK/aniruddha/newtimme/TIMME/code/utils.py", line 336, in multi_relation_load
    np.array(list(unlabeled_ids), dtype=np.int64)
ValueError: cannot convert float NaN to integer

**Comment by PatriciaXiao** [comment]
this is weird though, on my machine it used to work well. Can you do some prints and check which file does it not working on? I am also confused.

**Comment by PatriciaXiao** [comment]
So normally this kind of problems are caused directly by when you are trying to converge something that can not be converged into an integer. I wonder if this is caused by the versions of pandas? Or other possible issues. I can promise you that I didn't change a line of the code or data after I finished running my experiments. To be honest I am kind of shocked when seeing an issue like such.

**Comment by Souvic** [comment]
Ok, I am not working on this anymore. It may be issues with the libraries, not sure.
Since others did not mention any such issue and as I am currently not working on it, I am closing the issue.
